implements methods CRUD
kriian/Task-1 pull request #1
Opened 2023-04-20 13:03 UTC by kriian

2023-04-20 14:09 UTC, pdasilem requested changes

2023-04-20 14:09 UTC, pdasilem commented on pom.xml
> +<!--        <dependency>-->
лучше удалить закомментированное

2023-04-20 14:09 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/Main.java
> +        UserService service = new UserServiceImpl();
раскомментируй это

2023-04-20 14:09 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +    private final Connection connection;
коннекшн, стейтмент - инициализация в каждом методе

2023-04-20 14:09 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +            statementClose();
используй ресурсы трая

2023-04-20 14:09 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +            throw new RuntimeException(e);
смысл выбрасывать исключение? у тебя для чего кэтч блок?

2023-04-20 14:09 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/util/Util.java
> +    private static Connection connection;
не стоит здесь инициализировать коннекшн

2023-04-20 14:24 UTC, kriian commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +    private final Connection connection;
Глобальный стейтман мне нужен чтобы закрывать его.

2023-04-21 18:36 UTC, pdasilem approved these changes

2023-04-24 10:17 UTC, merged